version: 2.1

executors:
  java-19-docker:
    docker:
      - image: maven:3.9.1-amazoncorretto-19
    working_directory: ~/project

jobs:
  run-unit-tests:
    executor: java-19-docker
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            mvn install -DskipTests
      - run:
          name: Run unit tests
          command: |
            mvn test

  run-lint-code:
    executor: java-19-docker
    steps:
      - checkout
      - run:
          name: Run code linter
          command: |
            mvn checkstyle:check

  run-build-application:
    executor: java-19-docker
    steps:
      - checkout
      - run:
          name: Build application
          command: |
            mvn clean package
      - store_artifacts:
          path: target/QuestionsProcessorMock.jar
          destination: build-artifacts

workflows:
  version: 2
  test-workflow:
    jobs:
      - run-lint-code
      - run-unit-tests
      - run-build-application
    filters:
      pull_requests:
        only: main

