version: 2.1

executors:
  java-19-docker:
    docker:
      - image: maven:3.9.1-amazoncorretto-19
    working_directory: ~/project


jobs:
  run-unit-tests:
    executor: java-19-docker
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            mvn install -DskipTests
      - run:
          name: Run unit tests
          command: |
            mvn test

  run-lint-code:
    executor: java-19-docker
 
    steps:
      - checkout
      - run:
          name: Run code linter
          command: |
            mvn checkstyle:check

  run-build-application:
    executor: java-19-docker

    steps:
      - checkout
      - run:
          name: Build application
          command: |
            mvn clean package

      - store_artifacts:
          path: target/QuestionsProcessorMock.jar
          destination: build-artifacts
  build_and_push:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - generate-image-tag:
          command: |
            export DOCKER_TAG="my-docker-image-$(date +'%Y-%m-%d-%H-%M-%S')"
            echo "Docker tag is $DOCKER_TAG"
      - docker/build:
          image: mock-project-for-circleCI
          tag: $DOCKER_TAG
      - docker/push:
          image: mock-project-for-circleCI
          tag: $DOCKER_TAG
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

workflows:
  version: 2
  test-workflow:
    jobs:
      - run-lint-code
      - run-unit-tests
      - run-build-application
