version: 2.1

jobs:
  run-unit-tests:
    docker:
      - image: maven:3.9.1-amazoncorretto-19
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            mvn install -DskipTests
      - run:
          name: Run unit tests
          command: |
            mvn test

  lint-code:
    steps:
      - checkout
      - run:
          name: Run code linter
          command: |
            mvn checkstyle:check

  build-application:
    steps:
      - checkout
      - run:
          name: Build application
          command: |
            mvn clean package

      - store_artifacts:
          path: target/*.jar
          destination: build-artifacts


workflows:
  version: 2
  test-workflow:
    jobs:
      - run-unit-tests
