version: 2.1

jobs:
  run-unit-tests:
    docker:
      - image: maven:3.9.1-amazoncorretto-19
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            mvn install -DskipTests
      - run:
          name: Run unit tests
          command: |
            mvn test
    executor: docker-executor

workflows:
  version: 2
  test-workflow:
    jobs:
      - run-unit-tests
