version: 2.1

jobs:
  run-unit-tests:
    docker:
      - image: maven:3.9.5-openjdk-19-slim
    steps:
      - checkout  # Pasul pentru a verifica codul din repo-ul tău
      - run:
          name: Install dependencies
          command: |
             mvn install -DskipTests  # Pentru proiectele Maven
      - run:
          name: Run unit tests
          command: |
             mvn test
workflows:
  test-workflow:
    jobs:
      - run-unit-tests
